### PR TITLE
Got rid of indices migration operation

### PR DESCRIPTION
**Pull request by sebastianballesteros**

### CODE REVIEW

**Comment by sebastianballesteros** [comment]
I actually kept the 0032 migration but got rid of the "create indices part" I am still creating the index sets and index structures for test simplicity.

**Comment by UlysseFG** [comment]
Mmm they will have to go too at some point ... Up to you if you feel it's going to be too long we'll take this step.

**Comment by sebastianballesteros** [comment]
For now I think it is a quick and straight forward fix.

**Review by UlysseFG — APPROVED** [review]

**Review by ckostiw — APPROVED** [review]
I didn't find anything that needed to be changed. 👍

**Pull request merged**
