### PR TITLE
Correction to the infinium beadchip format.

### PR DESCRIPTION
**Pull request by UlysseFG**

### CODE REVIEW

**Comment by UlysseFG** [comment]
The cypress tests still fail. I will investigate further.

**Comment by jleblond** [comment]
2 Container creation fixtures (for front-end testing) template files were deleted?

Otherwise looks good to me. Do your cypress tests still fail?

**Comment by UlysseFG** [comment]
> 2 Container creation fixtures (for front-end testing) template files were deleted?
Nope only one the number 2 ... the other is just modified...

**Comment by jleblond** [comment]
I think it's a very great start for the front-end tests, I dont see those 'ResizableObserver' errors anymore. From the tests I ran, there are still some tests that are invalid though, maybe that could be done in a separate PR, but I think some lines of tests are  no longer valid. Let me know if it's the same for you, or if all the tests do pass.

**Pull request merged**
