### PR TITLE
Update requirements

### PR DESCRIPTION
**Pull request by ckostiw**
These updates solved `pip install -r requirements.txt` issues, where install was failing due to build errors during the installation process.

### CODE REVIEW

**Comment by UlysseFG** [comment]
Can you specify what build issues this fixes ?

**Comment by ckostiw** [comment]
> Can you specify what build issues this fixes ?

pip install was failing because of compilation errors in the sources of the modules I updated. Would you like me to roll back and record the error messages I ran in to?

**Comment by UlysseFG** [comment]
>  Would you like me to roll back and record the error messages I ran in to?
Yikes nope. But i am just wondering because we do not have these issues so i was wondering if those were Mac only issues (those!) or something we may have overlooked. We cannot expect to bump versions each time Mac decide to be temperamental ;).

**Review by UlysseFG — APPROVED** [review]
Haven't found any issue. I'll merge so we can test these for as long as possible before release.

**Pull request merged**
