### PR TITLE
Addition of new taxon to sample submission

### PR DESCRIPTION
**Pull request by UlysseFG**

### CODE REVIEW

**Review by ckostiw — CHANGES_REQUESTED** [review]
I checked out the branch and tried to open the template. Excel complains that the file needs repairs when I try to open it.
Screen Shot 2022-10-11 at 9 25 30 AM

**Comment by ckostiw** [comment]
I checked out the original template from master and I added the new taxon id to the index. Here's the updated file. Does it work for you?

[Sample_submission_v3_12_0.xlsx](https://github.com/c3g/freezeman/files/9756504/Sample_submission_v3_12_0.xlsx)

**Comment by sebastianballesteros** [comment]
I have the same problem as Chris when trying to open the new template. However, if I "recover" the file then it works. 
@ckostiw your's works fine.

**Comment by UlysseFG** [comment]
There was an filter field maybe that was the cause of the issue for you guys. I removed it... If it does not work, i will keep looking ... Your file does not have the new taxon in the comment. The first line of the Taxons column refer to the named range the 499 next lines refer to the range directly. I fixed that in my file. Try again if it does not work, i will get rid of the named ranged altogether.

**Comment by sebastianballesteros** [comment]
I am still having the same problem.

**Comment by UlysseFG** [comment]
I don't know if it's still your excel that makes troubles for nothing on my side it works ok but i guess i have no way to know... @sebastianballesteros can you convert my file and resubmit it so that it works for you guys ? @ckostiw file had a couple things to fix so i would prefer you taking mine to make sure it is the right version ... Make sure it still works with prefiling ...

**Comment by sebastianballesteros** [comment]
Done. Can you make sure it works @ckostiw  @UlysseFG? Thank you.

**Review by ckostiw — APPROVED** [review]

**Comment by ckostiw** [comment]
The template now loads for me without any problems.

**Pull request merged**
