### PR TITLE
Sample pooling v4_12_0

### PR DESCRIPTION
**Pull request by nafiz1001**

### CODE REVIEW

**Comment by UlysseFG** [comment]
Missing :
- Add "Illumina iSeq100" on the list column I

**Comment by UlysseFG** [comment]
Info tab fields order is no longer correct.

**Comment by nafiz1001** [comment]
> Missing :
> 
>     * Add "Illumina iSeq100" on the list column I

> Info tab fields order is no longer correct. You do not need to correct the test templates, just the template itself.

Should I make the same updates to the test templates?

**Comment by nafiz1001** [comment]
I'll let Andres review the template changes

**Pull request merged**
