### PR TITLE
Fix Sample fetching in Labwork Step Overview Panel

### PR DESCRIPTION
**Pull request by nafiz1001**

### CODE REVIEW

**Comment by samouzegar10** [comment]
i dont have much to say about this pr, you added a return and modified the main component. looks good to me

**Comment by UlysseFG** [comment]
I still get forever loading tables... When loading a group with a lot of sample and then right away switching to another group i get forever loading second group. This seem to be related to the abort (i get an abort error in the console).

**Comment by nafiz1001** [comment]
> I still get forever loading tables... When loading a group with a lot of sample and then right away switching to another group i get forever loading second group. This seem to be related to the abort (i get an abort error in the console).

(╯°□°)╯︵ ┻━┻

**Comment by UlysseFG** [comment]
ᑐᙵᓱᒋᑦ

**Review by UlysseFG — APPROVED** [review]

**Pull request merged**
