### PR TITLE
Sample submission requested modifications

### PR DESCRIPTION
**Pull request by UlysseFG**

### CODE REVIEW

**Review by ckostiw — APPROVED** [review]

**Review by ckostiw — CHANGES_REQUESTED** [review]
The dropdown in the Sample Coord column is not working for me, and if I enter "A01" manually I get a validation error.

Should we also move the Reception date column in the Pool Submission sheet to be consistent?

**Comment by UlysseFG** [comment]
> The dropdown in the Sample Coord column is not working for me, and if I enter "A01" manually I get a validation error.
OK i'll check

> Should we also move the Reception date column in the Pool Submission sheet to be consistent?
Yeah most likely.. it is a work in progress. I was thinking over a couple other suggestion. One is to move the date out to have to enter it only once for the whole template.

**Comment by UlysseFG** [comment]
I found a bug in the sample submission template ingestion so i decided to push ahead these changes and i'll updade when we get some feedback from the lab.

**Review by ckostiw — CHANGES_REQUESTED** [review]
The SampleCoords dropdown in the submission template is still not working for me (clicking on it does nothing) and five tests are failing:

```
FAILED fms_core/tests/test_services/experiment_run_info_test.py::ExperimentRunInfoTemplatesTestCase::test_illumina_experiment_run - Exception: Failed to import template Sample_submission_v4_0_0.xlsx
FAILED fms_core/tests/test_services/experiment_run_info_test.py::ExperimentRunInfoTemplatesTestCase::test_mgi_experiment_run - Exception: Failed to import template Sample_submission_v4_0_0.xlsx
FAILED fms_core/tests/test_services/experiment_run_info_test.py::ExperimentRunInfoTemplatesTestCase::test_service_get_run_info_for_experiment - Exception: Failed to import template Sample_submission_v4_0_0.xlsx
FAILED fms_core/tests/test_services/experiment_run_info_test.py::ExperimentRunInfoTemplatesTestCase::test_service_start_experiment_run_processing - Exception: Failed to import template Sample_submission_v4_0_0....
FAILED fms_core/tests/test_template_importers/sample_submission_test.py::SampleSubmissionTestCase::test_import - AssertionError: False != True
```

**Comment by UlysseFG** [comment]
> The SampleCoords dropdown in the submission template is still not working for me (clicking on it does nothing) and five tests are failing:
> 
> ```
> FAILED fms_core/tests/test_services/experiment_run_info_test.py::ExperimentRunInfoTemplatesTestCase::test_illumina_experiment_run - Exception: Failed to import template Sample_submission_v4_0_0.xlsx
> FAILED fms_core/tests/test_services/experiment_run_info_test.py::ExperimentRunInfoTemplatesTestCase::test_mgi_experiment_run - Exception: Failed to import template Sample_submission_v4_0_0.xlsx
> FAILED fms_core/tests/test_services/experiment_run_info_test.py::ExperimentRunInfoTemplatesTestCase::test_service_get_run_info_for_experiment - Exception: Failed to import template Sample_submission_v4_0_0.xlsx
> FAILED fms_core/tests/test_services/experiment_run_info_test.py::ExperimentRunInfoTemplatesTestCase::test_service_start_experiment_run_processing - Exception: Failed to import template Sample_submission_v4_0_0....
> FAILED fms_core/tests/test_template_importers/sample_submission_test.py::SampleSubmissionTestCase::test_import - AssertionError: False != True
> ```

Did you collectstatic ?

**Review by ckostiw — APPROVED** [review]

**Pull request merged**
