### PR TITLE
Add multiple study from sample submission.

### PR DESCRIPTION
**Pull request by UlysseFG**

### CODE REVIEW

**Review by ckostiw — CHANGES_REQUESTED** [review]
The sample submission template needs to be updated - data validation on the column blocks the user from entering multiple studies, eg. "A-B-C"

**Comment by ckostiw** [comment]
Strange. If I run this backend with my current frontend, the frontend shows the samples at random steps (extraction, library qc, experiment run, etc..). I'll need to merge master into my branch, I think, and solve some issues. :)

**Comment by UlysseFG** [comment]
Ok added some validation to make sure we don't go queuing sample to library steps and removed the Study dropdown.

**Comment by ckostiw** [comment]
To test, I tried submitting a library to two studies - once that starts on step Library QC, and the other that starts with Extraction DNA. The error was caught and I got this message: 
`Row #9: queue_to_study - Step Extraction (DNA) expected Unextracted sample but Sample LIB1 does not match that sample type.`

I think it would be useful to include the study letter in the message, to indicate which study could not accept the sample.

**Pull request merged**
