### PR TITLE
Feature #1750:  Group Similar Warnings for Template Submission

### PR DESCRIPTION
**Pull request by nafiz1001**
https://206.12.92.46/issues/1750

### CODE REVIEW

**Comment by nafiz1001** [comment]
image
image

**Comment by ckostiw** [comment]
I think if that there are more than 10 rows with errors then we should display something like: 
"(Row # 11, 12, 13, 14, 15, 16, 17, 18, 19, 20... (+231 others)"

The lab's templates will usually have at least a hundred sample, and I'm pretty sure there will be a lot of cases where the same warning is applied to every sample.

Screen Shot 2023-07-04 at 3 04 52 PM

**Comment by nafiz1001** [comment]
image
image
image

**Comment by UlysseFG** [comment]
The index validation tool warnings are not updated to the new format...

**Review by UlysseFG — APPROVED** [review]

**Pull request merged**
