### PR TITLE
Use Hash in URL for Tabs

### PR DESCRIPTION
**Pull request by nafiz1001**

### CODE REVIEW

**Comment by UlysseFG** [comment]
It is looking good. The only thing i saw that was a bit strange is that when you backtrack in the browser the previous tab stays bluish instead of becoming grey... If you click the page it goes away. Not sure that is really an issue.
I would add that hash ref to all the sections (container, sample, individual, project, experiment, ...).

**Comment by nafiz1001** [comment]
> It is looking good. The only thing i saw that was a bit strange is that when you backtrack in the browser the previous tab stays bluish instead of becoming grey... If you click the page it goes away. Not sure that is really an issue. I would add that hash ref to all the sections (container, sample, individual, project, experiment, ...).

It happens to me when i backtrack and mouse click the tabs at the same time.

**Comment by ckostiw** [comment]
I applied this to all of the pages with <Tab> elements. It should be ready to merge.

**Review by ckostiw — COMMENTED** [review]
Ready for a final review. All <Tabs> views are now hooked up to the url.

**Review by UlysseFG — APPROVED** [review]

**Pull request merged**
